services:
  aws-tunnel:
    build: .
    container_name: aws-tunnel
    env_file: .env
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./:/app/
    network_mode: "host"
    entrypoint: ["/app/scripts/entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 128M
  
  console:
    build: .
    volumes:
      - .:/app/
    working_dir: /app
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 128M
    
  print:
    build: .
    container_name: aws-tunnel
    env_file: .env
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./:/app/
    network_mode: "host"
    entrypoint: ["/app/scripts/mysql/print.sh"]
    deploy:
      resources:
        limits:
          memory: 128M

  connect:
    build: .
    container_name: aws-tunnel
    env_file: .env
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./:/app/
    network_mode: "host"
    entrypoint: ["/app/scripts/mysql/connect.sh"]
    deploy:
      resources:
        limits:
          memory: 128M
